name: codesign
description: A standalone app to codesign Mac engine binaries.
version: 1.0.0
homepage: https://github.com/flutter/cocoon

environment:
  sdk: '>=2.17.0-266.1.beta <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  archive: ^3.3.0
  args: ^2.3.1
  crypto: ^3.0.1
  fake_async: ^1.3.0
  file: ^6.1.2
  flutter_lints: ^2.0.1
  logging: ^1.0.2
  meta: ^1.7.0
  platform: ^3.1.0
  process: ^4.2.4



