# See Dependabot documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/test_utilities"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/licenses"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/codesign"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/device_doctor"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/dashboard"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/app_dart"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "pub"
    directory: "/auto_submit"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "docker"
    directory: "/app_dart"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "docker"
    directory: "/release"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "docker"
    directory: "/auto_submit"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
  - package-ecosystem: "gomod"
    directory: "/tooling"
    schedule:
      interval: "daily"
    labels:
      - "team"
      - "team: infra"
      - "autosubmit"
    allow:
      - dependency-name: "github.com/slsa-framework/slsa-verifier/v2"
