name: license_checks
description: Script to check licenses.

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  path: 1.9.0
  platform: 3.1.4

dev_dependencies:
  mockito: 5.4.4
  test_api: 0.7.1
