name: license_checks
description: Script to check licenses.

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  path: ^1.8.3
  platform: ^3.1.0

dev_dependencies:
  mockito: ^5.3.2
  test_api: ^0.4.17
