name: cocoon_integration_test
description: Integration testing environment for Cocoon.
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  appengine: ^0.13.11
  buildbucket:
    path: ../buildbucket-dart
  cocoon_common:
    path: ../cocoon_common
  cocoon_server:
    path: ../cocoon_server
  cocoon_server_test:
    path: ../cocoon_server_test
  cocoon_service:
    path: ../../app_dart
  collection: ^1.19.1
  fixnum: 1.1.1
  github: 9.25.0
  googleapis: 14.0.0
  googleapis_auth: ^2.0.0
  gql: ^1.0.1
  graphql: ^5.2.3
  http: ^1.2.1
  jose_plus: ^0.4.7
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  mockito: ^5.6.3
  neat_cache: ^2.0.5
  path: ^1.9.1
  process: ^5.0.5
  retry: ^3.1.2
  test: ^1.26.3
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  lints: ^6.0.0