name: cocoon_analyze
description: Cocoon static analysis scripts
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  file: 7.0.0
  path: 1.8.3
  platform: 3.1.2

dev_dependencies:
  mockito: 5.4.2
  test_api: 0.6.1
