name: cocoon_analyze
description: Cocoon static analysis scripts
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  file: 7.0.1
  path: 1.9.0
  platform: 3.1.6

dev_dependencies:
  mockito: 5.4.5
  test_api: 0.7.4
