name: buildbucket
description: LUCI Buildbucket library. Protos and utilities to communicate with LUCI buildbucket service.
version: 1.0.3
repository: https://github.com/flutter/cocoon/tree/main/packages/buildbucket-dart

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  protoc_plugin: 20.0.1
  fixnum: 1.1.0
  protobuf: 2.1.0

dev_dependencies:
  lints: 2.1.0
  test: 1.24.2
