name: cocoon
version: 0.0.1
homepage: https://github.com/flutter/cocoon

dependencies:
  angular: ^5.0.0-beta
  angular_forms: 2.0.0-beta+2
  args:
  browser:
  charted:
  js:
  http:
  meta:

dev_dependencies:
  test:
  build_runner:
  build_test:
  build_web_compilers:

environment:
  sdk: ">=2.0.0-dev.64.2 <3.0.0"