name: cocoon
version: 0.0.2
homepage: https://github.com/flutter/cocoon

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: 5.3.0
  angular_forms: 2.0.0
  args:
  js:
  http:
  meta:
  json_annotation:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  test:
  build_test:
  json_serializable:
  # Enables the `pub run build_runner` command
  build_runner: ^1.1.2
  # Includes the JavaScript compilers
  build_web_compilers: ^1.0.0
  flutter_web_test: any

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web.git
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web.git
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web.git
      path: packages/flutter_web_test
