name: cocoon
version: 0.0.1
homepage: https://github.com/flutter/cocoon
environment:
  sdk: '>=2.0.0-dev.58.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.21
  args: ^0.13.4
  browser: ^0.10.0
  charted: ^0.4.0
  js: ^0.6.0
  http: ^0.11.3
  meta: ^0.12.1
dev_dependencies:
  test: ^0.12.14
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    entry_points:
      - web/benchmarks.dart
      - web/build.dart
      - web/index.dart
    resolved_identifiers:
      Client: 'package:http/http.dart'
- $dart2js:
    minify: true
    sourceMaps: true
