name: device_doctor
description: A Dart tool to check device healthiness and implement recovery mechanisms to get the device back to a working state.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.2
  meta: ^1.1.7
  path: ^1.6.4
  process: ^3.0.12
  yaml: ^2.1.15

dev_dependencies:
  test: ^1.9.0
  mockito: ^4.1.0
