name: device_doctor
description: A Dart tool to check device healthiness and implement recovery mechanisms to get the device back to a working state.
version: 1.0.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args: ^1.5.2
  logging: ^0.11.4
  meta: ^1.1.7
  path: ^1.6.4
  process: ^4.2.1
  retry: ^3.0.1
  yaml: ^3.1.0
  analyzer: ^1.7.2

dev_dependencies:
  test: ^1.16.5
  mockito: ^4.1.0
