name: cocoon_agent
version: 0.0.1
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Scripts that run Cocoon checklist tasks
homepage: https://github.com/flutter/cocoon

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  args: ^0.13.0
  browser: ^0.10.0
  charted: ^0.4.0
  dart_to_js_script_rewriter: ^1.0.0
  firebase: ^0.6.6
  firebase_rest: ^0.1.3
  http: ^0.11.3
  intl: ^0.12.7
  meta: ^0.12.1
  path: ^1.3.0
  stack_trace: ^1.6.5

dev_dependencies:
  test: ^0.12.13
  collection: ^1.8.0

transformers:
  - dart_to_js_script_rewriter
