name: device_doctor
description: A Dart tool to check device healthiness and implement recovery mechanisms to get the device back to a working state.
version: 1.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  analyzer: 5.13.0
  args: 2.4.2
  logging: 1.2.0
  meta: 1.9.1
  path: 1.8.3
  process: 5.0.0
  retry: 3.1.2
  yaml: 3.1.2

dev_dependencies:
  build_runner: 2.4.6
  fake_async: 1.3.1
  mockito: 5.4.2
  test: 1.24.5
