name: device_doctor
description: A Dart tool to check device healthiness and implement recovery mechanisms to get the device back to a working state.
version: 1.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  analyzer: 6.4.1
  args: 2.6.0
  logging: 1.2.0
  meta: 1.16.0
  path: 1.9.0
  process: 5.0.2
  retry: 3.1.2
  yaml: 3.1.2

dev_dependencies:
  build_runner: 2.4.13
  fake_async: 1.3.2
  mockito: 5.4.4
  test: 1.25.8
