name: device_doctor
description: A Dart tool to check device healthiness and implement recovery mechanisms to get the device back to a working state.
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  args: 2.7.0
  file: any
  logging: 1.3.0
  meta: 1.17.0
  path: 1.9.1
  platform: any
  process: 5.0.5
  retry: 3.1.2
  yaml: 3.1.3

dev_dependencies:
  build_runner: 2.10.1
  fake_async: 1.3.3
  mockito: 5.5.1
  test: 1.26.3
