name: Test app_dart

on:
  pull_request:
    branches: [main]
    paths:
      - "app_dart/**"
      - "packages/**"
      - ".github/workflows/app_dart_tests.yaml"
  push:
    branches: [main]

jobs:
  test-app-dart:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_dart

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: stable
          architecture: x64 # only needed for running locally (mac)

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get packages
        run: |
          flutter pub get

      - name: dart analyze app_dart
        run: |
          dart analyze --fatal-infos

      - name: dart format app_dart
        run: |
          dart format --set-exit-if-changed .

      - name: dart test app_dart
        run: |
          dart test test
