name: Common workflows

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  common-validations:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e
        with:
          channel: stable

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run analyze.dart
        working-directory: analyze
        run: |
          flutter pub get 
          dart --enable-asserts analyze.dart

      - name: Run cocoon_code_health
        run: |
          flutter pub get
          dart run dev/cocoon_code_health/bin/check.dart

      - name: Run license check
        working-directory: licenses
        run: |
          flutter pub get
          dart run check_licenses.dart
