name: no-response-test

# Declare default permissions as read only.
permissions: read-all

on:
  pull_request:
    paths:
      - 'gh_actions/third_party/no-response/**'
      - '.github/workflows/no-response_test.yaml'
      - '.github/workflows/no-response_publish.yaml'
jobs:
  unitTest:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'flutter/cocoon' }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.release.tag_name }}
          sparse-checkout: 'gh_actions/third_party/no-response'
          sparse-checkout-cone-mode: false
      - name: move_package_to_root
        run: |
          mv gh_actions/third_party/no-response/.[!.]* ./
          rm -rf gh_actions
      - name: ls
        run: ls -la
      - name: npm_ci
        run: npm ci
      - name: npm_run_ci
        run: npm run ci
      - name: npm_run_build
        run: npm run build
